<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/Index/view/web/layout.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC&family=Shrikhand&display=swap" rel="stylesheet">
    <?= $head ?>
</head>
<body>
<div class="header">
    <div class="header__top">
        <a href="http://localhost" class="header__top__title">
            SuperStore
        </a>
        <div class="header__top__add">
            <a href="/catalog/admin/product/" class="header__top__add__button">
                ADMIN
            </a>

        </div>
        <form action="/" id="search" method="get" class="header__top__search">
            <input type="text" name="query" class="header__top__search__field"
                <?php if (isset($query)) {echo 'value = "'.$query.'"';} ?>
            >
            <input type="submit" value="Search" class="header__top__search__button">
        </form>
    </div>
    <div class="header__bot">
        <div class="header__bot__categories">
            <?php
            foreach ($categories as $category){
                ?>
                <button class="header__bot__categories__item <?php if ($category->getId() == $_GET['category']) {
                    echo 'header__bot__categories__item--chosen';} ?>" onclick="addCategorySort(<?= $category->getId() ?>)"
                >
                    <?= $category->getName() ?>
                </button>
                <?php
            }
            ?>
        </div>
    </div>
</div>
<script>

    function togglePopup(){
        document.querySelector(".popup").classList.toggle("popup--open")
        document.querySelector(".popup__background").classList.toggle("popup--open")
    }

    $("#search").on('submit', function(e){
        e.preventDefault();
        let query = e.target[0].value;
        const urlParams = new URLSearchParams(window.location.search);
        let url = "http://localhost/";

        if (urlParams.get("sort")){
            url = url + "?sort=" + urlParams.get("sort")
        }

        if (urlParams.get("category")) {
            if (urlParams.get("sort")) {
                url = url + "&category=" + urlParams.get("category")
            } else {
                url = url + "?category=" + urlParams.get("category")
            }
        }

        if (query.trim() !== '' && query) {
            if (urlParams.get("sort") || urlParams.get("category")) {
                url = url + "&query=" + query
            } else {
                url = url + "?query=" + query
            }
        }

        window.location.href = url
    })

    function addCategorySort(categoryId){
        const urlParams = new URLSearchParams(window.location.search);
        let url = "http://localhost/"
        if (categoryId) {
            url = url + '?category=' + categoryId;
            if (urlParams.get("sort")){
                url = url + "&sort=" + urlParams.get("sort")
            }
            if (urlParams.get("query")){
                url = url + "&query=" + urlParams.get("query")
            }
        }
        window.location.href = url
    }

</script>
<?php
echo $pageContent;
?>

</body>
</html>
