<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/Catalog/view/web/edit.css">
</head>
<div class="edit">

    <div id="editMessage"></div>

    <form class="edit__form" action="/Catalog/Product/Edit" method="post" id="editProduct">
        <input required placeholder="Name" name="name"

               type="text" class="edit__form__input" id="form__name" value=<?= $product->getName() ?>
        >
        <input placeholder="Number (SKU)"
               name="sku" type="text" class="edit__form__input" id="form__sku" value=<?= $product->getSku() ?>
        >

        <input required placeholder="Price" name="price"
               type="number" class="edit__form__input" id="form__price" value=<?= $product->getPrice() ?>
        >

        <input placeholder="Photo" name="photo" type="file"
               class="edit__form__input" id="form__photo" value=<?= $product->getImageUrl() ?>
        >

        <textarea placeholder="Description" name="descr"
                  class="edit__form__input" id="form__descr" value=<?= $product->getDescription() ?>
        ><?= $product->getDescription() ?></textarea>

        <select required name="category" class="edit__form__input" id="form__category">
            <?php
            foreach ($categories as $category){
                ?>
                <option value=<?= $category->getId()?>
                        <?php if($category->getId() == $product->getCategoryId()){echo "selected";} ?> >
                    <?= $category->getName() ?>
                     </option>
                <?php
            }
            ?>
        </select>

        <input id="id" name="id" type="hidden" value=<?= $product->getId() ?>>
        <input type="submit" class="edit__form__input" id="form__submit">

    </form>
</div>
<script>
    $("#editProduct").on('submit', function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: $("#editProduct")[0].action,
            data: new FormData(this),
            dataType: 'json',
            contentType: false,
            cache: false,
            processData:false,
            beforeSend: function(){
                $('#form__submit').attr("disabled","disabled");
            },
            success: function(){
                $("#form__submit").removeAttr("disabled");
                window.location.replace('http://localhost/catalog/admin/product/#'+<?= $product->getId() ?>);
            }
        });
    });
</script>

