<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="/Admin/view/web/layout.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Alegreya+Sans+SC&family=Shrikhand&display=swap" rel="stylesheet">
    <?= $head ?>
</head>
<body>
<div class="header">
    <div class="header__top">
        <a href="http://localhost" class="header__top__title">
            SuperStore
        </a>
        <div class="header__top__add">
            <button onclick="togglePopup()" class="header__top__add__button">
                Add Product
            </button>
        </div>
    </div>
</div>

<div class="popup__background" onclick=togglePopup()></div>
<div class="popup">
    <form class="popup__form" action="/catalog/product/save" method="post" id="addProduct">
        <p id="successMessage"></p>
        <input required placeholder="Name" name="name" type="text" class="popup__form__input" id="form__name">
        <input placeholder="Number (SKU)" name="sku" type="text" class="popup__form__input" id="form__sku">
        <input required placeholder="Price" name="price" type="number" class="popup__form__input" id="form__price">
        <select required name="category" class="popup__form__input" id="form__category">
            <?php
            foreach ($categories as $category){
                ?>
                <option value=<?= $category->getId() ?>><?= $category->getName() ?></option>
                <?php
            }
            ?>
        </select>
        <label for="form__photo" id="uploadLabel">
            Click here to set the image
            <input placeholder="Photo" name="photo" type="file" class="popup__form__input" id="form__photo">
        </label>
        <textarea placeholder="Description" name="descr" class="popup__form__input" id="form__descr"></textarea>
        <div>
            <input type="submit" class="popup__form__input" id="form__submit" value="Save product">
        </div>
    </form>
</div>
<script>

    function togglePopup(){
        document.querySelector(".popup").classList.toggle("popup--open")
        document.querySelector(".popup__background").classList.toggle("popup--open")
    }


    $("#addProduct").on('submit', function(e){
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: $("#addProduct")[0].action,
            data: new FormData(this),
            dataType: 'json',
            contentType: false,
            cache: false,
            processData:false,
            success: function(response){
                if(response['success'] === true){
                    $("#successMessage").html(response['message']);
                    setTimeout(function(){
                        location.reload();
                    }, 1000);
                }
            }
        });
    });

</script>
<?php
echo $pageContent;
?>

</body>
</html>
